project:
  type: website
  output-dir: docs
  
website:
  title: "Luca Alioto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/lucaalioto
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "Luca Alioto"

format:
  html:
    theme:
      - sandstone
      - html/custom.scss
    toc: true
    highlight-style: monokai
    
editor: source
